# Generated by Django 6.0.4 on 2026-05-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('father_name', models.CharField(max_length=200)),
                ('father_phone', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=200)),
                ('mother_phone', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=200)),
                ('prev_qualification', models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('Diploma', 'Diploma'), ('Degree', 'Degree')], max_length=20)),
                ('prev_course_name', models.CharField(max_length=200)),
                ('prev_college_name', models.CharField(max_length=200)),
                ('prev_college_place', models.CharField(max_length=200)),
                ('year_of_passing', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
