# Generated by Django 6.0.4 on 2026-05-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='user',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(default='muhammedfahim438@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
